---
- hosts: knode
  tasks:
  - name: Install kubelet ...
    yum:
      name:
         - kubelet
         - kubeadm
         - kubectl
      state: latest
  - name: 
    shell: |
      'VERSION="v1.23.0"'
      curl -L https://github.com/kubernetes-sigs/cri-tools/releases/download/$VERSION/crictl-${VERSION}-linux-amd64.tar.gz --output crictl-${VERSION}-linux-amd64.tar.g          tar zxvf crictl-$VERSION-linux-amd64.tar.gz -C /usr/local/bin
      rm -f crictl-$VERSION-linux-amd64.tar.gz
      crictl config --set runtime-endpoint="unix:///run/containerd/containerd.sock"
      crictl images

  - name: systemctl enable containerd
    service:
      name: kubelet
      state: started
      enabled: yes

